#!/usr/bin/env python3

tags = {
	"561LIST": 			"Foreign Financial Institution Subject To 31 CFR 561",
	"BALKANS": 			"Western Balkans Stablization Regulations (31 CFR 548)",
	"BELARUS":	 		"Belarus Sanctions Regulations (31 CFR 548)",
	"BPI-PA": 			"Blocked Pending Investigation Under Patriot Act",
	"BURMA": 			"Burmese Sanctions Regulations (31 CFR 537)",
	"BURUNDI": 			"Burundi Sanctions Executive Order",
	"CAR": 				"Central African Republic Sanctions (31 CFR 553)",
	"COTED": 			"Cote d'Ivoire Sanctions Regulations (31 CFR 543)",
	"CUBA": 			"Cuban Assets Control Regulations (31 CFR 515)",
	"CYBER": 			"Cybersecurity Sanctions (Executive Order 13687)",
	"CYBER2": 			"Cybersecurity Sanctions (Executive Order 13722)",
	"DARFUR": 			"Darfur Sanctions Regulations (31 CFR 547)",
	"DPRK": 			"North Korea Sanctions Regulations (31 CFR 510)",
	"DPRK2": 			"North Korea / Executive Order 13687",
	"DPRK3": 			"North Korea / Executive Order 13722",
	"DRCONGO": 			"Democratic Republic of the Congo Sanctions Regulations (31 CFR 547)",
	"EO13622": 			"Executive Order 13622",
	"EO13645": 			"Executive Order 13645",
	"FSE-SY": 			"Foreign Sanctions Evaders - Syria (EO 13608)",
	"FSE-IR": 			"Foreign Sanctions Evaders - Iraq (EO 13608)",
	"FSE-WMD": 			"Foreign Sanctions Evaders - WMD Non-Proliferation (EO 13608)",
	"FSE-SDGT": 		"Foreign Sanctions Evaders - Anti-Terrorism (EO 13608)",
	"FTO": 				"Foreign Terrorist Organization Sanctions Regulations (31 CFR 597)",
	"HRIT-SY": 			"Syria Sanctions (EO 13606)",
	"HRIT-IR": 			"Iran Sanctions (EO 13606)",
	"IFCA": 			"Iran Freedom and Counter-Proliferation Act of 2012",
	"IFSR": 			"Iranian Financial Sanctions Regulations (31 CFR 561)",
	"IRAN": 			"Itanian Transactions and Sanctions Regulations (31 CFR 560)",
	"IRAN-HR": 			"Iran Sanctions (EO 13553)",
	"IRAN-TRA": 		"Iran Sanctions (EO 13628)",
	"IRAQ2": 			"Iraq Sanctions (EO 13315, EO 13350)",
	"IRAQ3": 			"Iraq Sanctions (EO 13438)",
	"IGRC": 			"Iranian Financial Sanctions Regulations (31 CFR 549)",
	"ISA": 				"Iran Sanctions Act",
	"JADE": 			"Burma Sanctions (Pub. L. 110-286)",
	"LEBANON": 			"Lebanon Sanctions Regulations (31 CFR 549)",
	"LIBERIA": 			"Former Liberian Regimes of Charles Taylor Sanctions Regulations (31 CFR 593)",
	"LIBYA2":			"Libyan Sanctions (31 CFR 570)",
	"LIBYA3":			"Libyan Sanctions (EO 13726)",
	"MAGNIT":			"Sergei Magnitsky Rule of Law Accountability Act of 2012​",
	"NPWMD":			"Weapons of Mass Destruction Proliferators Sanctions Regulations, 31 CFR 544​",
	"NS-ISA":			"Non-SDN Iranian Sanctions Act (EO 13574)",
	"NS-PLC": 			"Non-SDN Palestinian Legislative Council List (31 CFR 594)",
	"SDGT":				"Global Terrorism Sanctions Regulations (31 CFR 594)",
	"SDNT":				"Narcotics Trafficking Sanctions Regulations (31 CFR 598)",
	"SDNTK": 			"Foreign Narcotics Kingpin Sanctions Regulations (31 CFR 598)",
	"SDT":				"Terrorism Sanctions Regulations (31 CFR 595)",
	"SOMALIA":			"Somalia Sanctions Regulations (31 CFR 551)",
	"SUDAN":			"Sudanese Sanctions Regulations (31 CFR 538)",
	"SOUTH SUDAN": 		"South Sudan Sanctions Regulations (31 CFR 558)",
	"SYRIA":			"Syrian Sanctions Regulations (31 CFR 542)",
	"TCO":				"Transnational Criminal Sanctions Regulations (31 CFR 590)",
	"UKRAINE-EO13660":	"Ukraine Sanctions (EO 13660)",
	"UKRAINE-EO13661":	"Ukraine Sanctions (EO 13661)",
	"UKRAINE-EO13662":	"Ukraine Sanctions (EO 13662)",
	"VENEZUELA":		"Venezuela Sanctions (EO 13685)",
	"YEMEN":			"Yemen Sanctions Regulations (31 CFR 552)",
	"ZIMBABWE":			"Zimbabwe Sanctions Regulations (31 CFR 541)"
}